#alermanager.yml
global:
  slack_api_url: 'https://hooks.slack.com/services/...' # add here your webhook url

route:
  receiver: slack-notifier
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 2m

receivers:
  - name: slack-notifier
    slack_configs:
      - channel: '#monitoring'
        send_resolved: true
        title: "⚠️ [{{ .CommonLabels.application }}] Error Alert!"
        text: |-
          *Exception:* {{ .CommonAnnotations.exception }}
          *Error Message:* {{ .CommonAnnotations.error_message }}
          *Timestamp:* {{ (index .Alerts 0).StartsAt }}
          *Application:* {{ .CommonLabels.application }}
          *Alert Received At:* {{ .CommonLabels.alert_received_at }}
          *Severity:* {{ .CommonLabels.severity }}
          *Details:* {{ .CommonAnnotations.details }}



